WIP: Exp 201609
tracer-x/klee-examples pull request #66
Opened 2016-09-16 11:22 UTC by feliciahalim

Modify Coreutils Makefile and Add a new script to run the experiment.

2016-09-19 02:07 UTC, domainexpert requested changes
Also, please do not forget to update `README.md` with an instruction on how to run the experiment.

2016-09-19 02:07 UTC, domainexpert commented on coreutils/Makefile
> +%.kleetest: build sandbox
Maybe `%.klee-exp-201609` as a target name is clearer.

2016-09-19 02:07 UTC, domainexpert commented on exp-201609.sh
> +#!/bin/bash
This loop can be implemented within the `coreutils/Makefile` itself, as a new `exp-201609:` target. In this way, we don't need a separate shell file.

2016-09-19 09:39 UTC, feliciahalim commented
@domainexpert Thank you for the feedback. I have updated it accordingly with added `sloccount` in` .klee-exp-201609` target.

2016-09-20 00:57 UTC, domainexpert commented on coreutils/Makefile
> +exp-201609:
@feliciahalim Would you please add a comment here explaining this target.

2016-09-20 00:57 UTC, domainexpert requested changes

2016-09-20 00:58 UTC, domainexpert commented
@feliciahalim Would you please also remove the WIP: from the title of this PR, as this is a PR that is complete.

2016-09-20 05:32 UTC, feliciahalim commented
@domainexpert I have updated `coreutils/Makefile ` with a comment, updated README.md by giving instructions to run exp-201609 experiment, and also updated this PR title. Thank you.

2016-09-20 05:35 UTC, domainexpert approved these changes

2016-09-20 05:36 UTC, merged

2016-09-20 05:37 UTC, domainexpert commented
@feliciahalim Well done! Removing the branch now ...