Collect the experiment results into csv file
tracer-x/klee-examples pull request #67
Opened 2016-09-21 11:31 UTC by feliciahalim

.. By adding a new target in the coreutils Makefile.

2016-09-22 02:26 UTC, domainexpert commented on coreutils/Makefile
> +	echo "Directory,Time, #instructions,#completed paths,#error paths,#subsumed paths,Average branching depth of completed paths,Average branching depth of subsumption paths,Average instructions of comp
I think we also need:
1. `#program exit paths`. I know that this number should equal `#completed paths` - `#error paths` - `#subsumed paths`, but if there were anomalies, we would like to detect it.
2. Time for actual solver calls in subsumption check (ms).
3. Number of solver calls for subsumption check.
4. Number of solver calls for subsumption check that resulted in subsumption failure.
5. Average table entries per subsumption checkpoint.
6. Average solver calls per subsumption check.

2016-09-22 02:34 UTC, domainexpert commented on coreutils/Makefile
> +	for program in cut expand fmt fold join pr printf sort sum tail tsort uniq wc factor seq; \
Here the loop that iterates over `ext` should be the outer one, and the loop that iterates over `program` the inner loop. The experimental table will be easier to read with if the runs are first categorized according to the tool first before the individual problem.

2016-09-22 02:36 UTC, domainexpert requested changes
Some changes.

2016-09-22 11:25 UTC, feliciahalim commented
@domainexpert Thank you for the suggestion. I have added more data to be printed in the CSV file.

2016-09-23 06:26 UTC, domainexpert approved these changes

2016-09-23 06:27 UTC, domainexpert commented
LGTM.

2016-09-23 06:27 UTC, merged