Add new Target for running experiment coreutils LLBMC and also for co…
tracer-x/klee-examples pull request #73
Opened 2016-09-29 10:11 UTC by feliciahalim

…llecting data experiments

2016-09-29 10:15 UTC, feliciahalim commented
@domainexpert  When running coreutils with LLBMC, there's computer freeze problem from some coreutils program. Therefore, I limit the `-max-loop-iterations` into 5 instead of 10 because the greater the number, it is also more likely the computer freeze problem happen.

2016-09-30 04:27 UTC, domainexpert requested changes
Just some small requests.

2016-09-30 04:27 UTC, domainexpert commented on coreutils/Makefile
> +	echo "Program, Time of Performing transformations on LLVM IR,Time of Performing logical encoding,Time of Performing formula transformations,Time of Running SMT solver (STP with MiniSat), Total Time,
Please change "Time of Performing" to "Time for performing". Please note the capitalization.

2016-09-30 04:27 UTC, domainexpert commented on coreutils/Makefile
> +LLBMC_OPTIONS=--ignore-missing-function-bodies -function-name=main -max-loop-iterations=5 -max-function-call-depth=10
I think -max-loop-iterations=5 is fine, as 10 as I suggested was just a random guess.

2016-09-30 04:27 UTC, domainexpert commented on coreutils/Makefile
> +# This target is used for running coreutils experiment with LLBMC.
Maybe it would be good to add:
`# Arguments in PROGRAM_ARGS have lengths matching that of KLEE runs`

2016-09-30 04:27 UTC, domainexpert commented on coreutils/Makefile
> +llbmc-csv:
I suggest renaming the target to `csv-exp-201609-llbmc` to put it within the context of our September experiments.

2016-09-30 08:05 UTC, domainexpert requested changes
Thank you! Just a tiny little request.

2016-09-30 08:05 UTC, domainexpert commented on coreutils/Makefile
> +# This target is used for running coreutils experiment with LLBMC. #Arguments in PROGRAM_ARGS have lengths matching that of KLEE runs.
I think the earlier comment was fine, I meant perhaps just to add another line for extra explanation.

2016-09-30 08:45 UTC, feliciahalim commented
@domainexpert Thank you for the feedback. I have modified it accordingly.

2016-10-01 03:47 UTC, domainexpert commented
@feliciahalim Please remove the WIP from the title if this branch is ready to be merged.

2016-10-01 04:08 UTC, feliciahalim commented
@domainexpert  I have removed the WIP from the title. Thank you.

2016-10-01 05:07 UTC, domainexpert approved these changes

2016-10-01 05:08 UTC, merged

2016-10-01 05:08 UTC, domainexpert commented
Thank you @feliciahalim .